### ISSUE TITLE
Your git commit messages could improve :( 

### ISSUE THREAD

**Issue by eno93** [tarball69/downloader#1]
Currently they make it difficult to follow what your actually doing. Thank you for Tkrad.

https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

http://chris.beams.io/posts/git-commit/

**Comment by tarball69** [comment]
Hi eno93,
You're right, I'm a lazy coder. :smile:
Commit messages bother me up, but from now, I think I'll better take care of good practices in this domain.
Thank you for your feedback. :+1:
Regards.
